# Generated by Django 4.1.1 on 2022-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                default="https://ik.imagekit.io/ja17viwyaow/user-placeholder_2VLM6EtOW.png"
            ),
        ),
    ]
