# Generated by Django 4.1.1 on 2022-09-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_id",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="has_avatar",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.URLField(
                default="https://ik.imagekit.io/ja17viwyaow/avatar-placeholder_2VLM6EtOW.png"
            ),
        ),
    ]
